import 'presentation/pages/rich_food_directory/data/data_model/rich_food_model.dart';

List<RichFoodModel> carbsData = [
  RichFoodModel(
    image: carbsImages[0],
    name: "Grapefruit",
    size: 100,
    calories: 389,
    fat: 7,
    carbs: 66,
    protein: 17,
    saturatedFat: 1.2,
    cholesterol: 0,
    dietaryFiber: 11,
    monoUnsaturatedFat: 2.2,
    polyUnsaturatedFat: 2.5,
    potassium: 429,
    sodium: 2,
    sugar: 11,
  ),
  RichFoodModel(
    image: carbsImages[1],
    name: "Apples",
    size: 100,
    calories: 118,
    fat: 0.2,
    carbs: 28,
    protein: 1.5,
    saturatedFat: 0,
    polyUnsaturatedFat: 0.1,
    monoUnsaturatedFat: 0,
    dietaryFiber: 4.1,
    sugar: 4.1,
    cholesterol: 0,
    sodium: 9,
    potassium: 816,
  ),
  RichFoodModel(
    image: carbsImages[2],
    name: "Blueberries",
    size: 100,
    calories: 111,
    fat: 0.9,
    carbs: 23,
    protein: 2.6,
    saturatedFat: 0.2,
    polyUnsaturatedFat: 0.3,
    monoUnsaturatedFat: 0.3,
    dietaryFiber: 1.8,
    sugar: 1.8,
    cholesterol: 0,
    sodium: 5,
    potassium: 43,
  ),
  RichFoodModel(
    image: carbsImages[3],
    name: "Cantaloupe",
    size: 100,
    calories: 86,
    fat: 0.1,
    carbs: 20,
    protein: 1.6,
    saturatedFat: 0,
    polyUnsaturatedFat: 0,
    monoUnsaturatedFat: 0,
    dietaryFiber: 3,
    sugar: 3,
    cholesterol: 0,
    sodium: 5,
    potassium: 337,
  ),
  RichFoodModel(
    image: carbsImages[4],
    name: "Oranges",
    size: 100,
    calories: 357,
    fat: 0.4,
    carbs: 84,
    protein: 8,
    saturatedFat: 0.1,
    polyUnsaturatedFat: 0.2,
    monoUnsaturatedFat: 0.1,
    dietaryFiber: 3.3,
    sugar: 3.3,
    cholesterol: 0,
    sodium: 729,
    potassium: 168,
  ),
  RichFoodModel(
    image: carbsImages[5],
    name: "Bananas",
    size: 100,
    calories: 77,
    fat: 0.1,
    carbs: 17,
    protein: 2,
    saturatedFat: 0,
    polyUnsaturatedFat: 0,
    monoUnsaturatedFat: 0,
    dietaryFiber: 2.2,
    sugar: 2.2,
    cholesterol: 0,
    sodium: 6,
    potassium: 421,
  ),
  RichFoodModel(
    image: carbsImages[6],
    name: "Peaches",
    size: 100,
    calories: 247,
    fat: 3.4,
    carbs: 41,
    protein: 13,
    saturatedFat: 0.7,
    polyUnsaturatedFat: 0.6,
    monoUnsaturatedFat: 1.6,
    dietaryFiber: 7,
    sugar: 7,
    cholesterol: 0,
    sodium: 400,
    potassium: 248,
  ),
];

List carbsImages = [
  "https://mcbros.co.za/wp-content/uploads/2020/04/grapefruit.jpg",
  "https://lh3.googleusercontent.com/proxy/WWVnTlGmrUH0NeMo2eMC6mZ27DwlOvK4tRp9INE7L4J133KKRH2-frFPJWfCh1Uo3N6aEElprGPa-56tS9WlM_YHuTzQd9zr9X2M23qPjXCA8_7NQ74",
  "https://primaoliva.com/wp-content/uploads/2015/11/Wild-Blueberry-Balsamic-Vinegar.jpg",
  "https://gardenerspath.com/wp-content/uploads/2020/05/Sugar-Cube.jpg",
  "https://www.chuksprimeorganics.com/wp-content/uploads/2018/01/ORGANIC-PLANTS.jpg",
  "https://images.carriercms.com/image/upload/w_500,h_400,c_fill,g_center,q_auto,f_auto/v1543516192/carrier/carrier-global/food/bananas.jpg",
  "https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/articles/health_tools/the_health_benefits_of_peaches_slideshow/thinkstock_rf_peaches.jpg?resize=650px:*",
];

List<RichFoodModel> proteinData = [
  RichFoodModel(
    image: proteinImages[0],
    name: "Eggs",
    size: 100,
    calories: 389,
    fat: 7,
    carbs: 66,
    protein: 17,
    saturatedFat: 1.2,
    cholesterol: 0,
    dietaryFiber: 11,
    monoUnsaturatedFat: 2.2,
    polyUnsaturatedFat: 2.5,
    potassium: 429,
    sodium: 2,
    sugar: 11,
  ),
  RichFoodModel(
    image: proteinImages[1],
    name: "Walnuts",
    size: 100,
    calories: 118,
    fat: 0.2,
    carbs: 28,
    protein: 1.5,
    saturatedFat: 0,
    polyUnsaturatedFat: 0.1,
    monoUnsaturatedFat: 0,
    dietaryFiber: 4.1,
    sugar: 4.1,
    cholesterol: 0,
    sodium: 9,
    potassium: 816,
  ),
  RichFoodModel(
    image: proteinImages[2],
    name: "Almods",
    size: 100,
    calories: 111,
    fat: 0.9,
    carbs: 23,
    protein: 2.6,
    saturatedFat: 0.2,
    polyUnsaturatedFat: 0.3,
    monoUnsaturatedFat: 0.3,
    dietaryFiber: 1.8,
    sugar: 1.8,
    cholesterol: 0,
    sodium: 5,
    potassium: 43,
  ),
  RichFoodModel(
    image: proteinImages[3],
    name: "Peas",
    size: 100,
    calories: 86,
    fat: 0.1,
    carbs: 20,
    protein: 1.6,
    saturatedFat: 0,
    polyUnsaturatedFat: 0,
    monoUnsaturatedFat: 0,
    dietaryFiber: 3,
    sugar: 3,
    cholesterol: 0,
    sodium: 5,
    potassium: 337,
  ),
  RichFoodModel(
    image: proteinImages[4],
    name: "Pumkin Seeds",
    size: 100,
    calories: 357,
    fat: 0.4,
    carbs: 84,
    protein: 8,
    saturatedFat: 0.1,
    polyUnsaturatedFat: 0.2,
    monoUnsaturatedFat: 0.1,
    dietaryFiber: 3.3,
    sugar: 3.3,
    cholesterol: 0,
    sodium: 729,
    potassium: 168,
  ),
  RichFoodModel(
    image: proteinImages[5],
    name: "Tofu",
    size: 100,
    calories: 77,
    fat: 0.1,
    carbs: 17,
    protein: 2,
    saturatedFat: 0,
    polyUnsaturatedFat: 0,
    monoUnsaturatedFat: 0,
    dietaryFiber: 2.2,
    sugar: 2.2,
    cholesterol: 0,
    sodium: 6,
    potassium: 421,
  ),
];

List proteinImages = [
  "https://www.simplyhappyfoodie.com/wp-content/uploads/2019/07/air-fryer-boiled-eggs-2-500x375.jpg",
  "https://static.toiimg.com/thumb/msid-65873369,imgsize-205068,width-800,height-600,resizemode-75/65873369.jpg",
  "https://www.orissapost.com/wp-content/uploads/2019/10/almonds.jpg",
  "https://themicrogardener.com/wp-content/uploads/2013/05/Easy-Guide-to-Growing-Perfect-Peas-wm-600x450.jpg",
  "https://pipandebby.com/wp-content/uploads/2018/10/1018PumpkinSeeds511B1635post-1.jpg",
  "https://www.kayawell.com/Data/UserContentImg/2018/3/b1b977c9-671f-47af-8956-d4037e5a82fd.jpg",
];

List<RichFoodModel> fatData = [
  RichFoodModel(
    image: fatImages[0],
    name: "Oats",
    size: 100,
    calories: 389,
    fat: 7,
    carbs: 66,
    protein: 17,
    saturatedFat: 1.2,
    cholesterol: 0,
    dietaryFiber: 11,
    monoUnsaturatedFat: 2.2,
    polyUnsaturatedFat: 2.5,
    potassium: 429,
    sodium: 2,
    sugar: 11,
  ),
  RichFoodModel(
    image: fatImages[1],
    name: "Yams",
    size: 100,
    calories: 118,
    fat: 0.2,
    carbs: 28,
    protein: 1.5,
    saturatedFat: 0,
    polyUnsaturatedFat: 0.1,
    monoUnsaturatedFat: 0,
    dietaryFiber: 4.1,
    sugar: 4.1,
    cholesterol: 0,
    sodium: 9,
    potassium: 816,
  ),
  RichFoodModel(
    image: fatImages[2],
    name: "Brown Rice",
    size: 100,
    calories: 111,
    fat: 0.9,
    carbs: 23,
    protein: 2.6,
    saturatedFat: 0.2,
    polyUnsaturatedFat: 0.3,
    monoUnsaturatedFat: 0.3,
    dietaryFiber: 1.8,
    sugar: 1.8,
    cholesterol: 0,
    sodium: 5,
    potassium: 43,
  ),
  RichFoodModel(
    image: fatImages[3],
    name: "Sweet Potato",
    size: 100,
    calories: 86,
    fat: 0.1,
    carbs: 20,
    protein: 1.6,
    saturatedFat: 0,
    polyUnsaturatedFat: 0,
    monoUnsaturatedFat: 0,
    dietaryFiber: 3,
    sugar: 3,
    cholesterol: 0,
    sodium: 5,
    potassium: 337,
  ),
  RichFoodModel(
    image: fatImages[4],
    name: "Corn Flakes",
    size: 100,
    calories: 357,
    fat: 0.4,
    carbs: 84,
    protein: 8,
    saturatedFat: 0.1,
    polyUnsaturatedFat: 0.2,
    monoUnsaturatedFat: 0.1,
    dietaryFiber: 3.3,
    sugar: 3.3,
    cholesterol: 0,
    sodium: 729,
    potassium: 168,
  ),
  RichFoodModel(
    image: fatImages[5],
    name: "White Potato",
    size: 100,
    calories: 77,
    fat: 0.1,
    carbs: 17,
    protein: 2,
    saturatedFat: 0,
    polyUnsaturatedFat: 0,
    monoUnsaturatedFat: 0,
    dietaryFiber: 2.2,
    sugar: 2.2,
    cholesterol: 0,
    sodium: 6,
    potassium: 421,
  ),
  RichFoodModel(
    image: fatImages[6],
    name: "100 WHole Wheat Breads",
    size: 100,
    calories: 247,
    fat: 3.4,
    carbs: 41,
    protein: 13,
    saturatedFat: 0.7,
    polyUnsaturatedFat: 0.6,
    monoUnsaturatedFat: 1.6,
    dietaryFiber: 7,
    sugar: 7,
    cholesterol: 0,
    sodium: 400,
    potassium: 248,
  ),
];

List fatImages = [
  "https://i0.wp.com/post.healthline.com/wp-content/uploads/sites/3/2020/02/311409_2200-732x549.jpg?w=756&h=567",
  "https://image.freepik.com/free-photo/purple-yams-isolated_253984-354.jpg",
  "https://www.thefullpantry.com.au/wp-content/uploads/2017/10/rice-brown-medium.jpg",
  "https://images.indianexpress.com/2020/01/sweet-potato_1200.jpg",
  "https://www.thefullpantry.com.au/wp-content/uploads/2018/04/corn-flakes-1.jpg",
  "https://www.potatogoodness.com/wp-content/uploads/2019/02/white-potato-beauty-shot.png",
  "https://anoregoncottage.com/wp-content/uploads/2016/12/Soft-WW-Sandwich-Bread_650x650.jpg",
];
